#
# (C) Copyright 2014, Cavium Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-$(CONFIG_OCTEONTX_BGX) += octeontx_bgx.o
obj-$(CONFIG_OCTEONTX_VNIC) += nic_main.o nicvf_queues.o nicvf_main.o
obj-$(CONFIG_OCTEONTX_SMI) += octeontx_smi.o
obj-$(CONFIG_OCTEONTX_XCV) += octeontx_xcv.o
