#
# (C) Copyright 2014, Cavium Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-y = thunder_bgx.o nic_main.o nicvf_queues.o \
		nicvf_main.o thunderx_smi.o
obj-$(CONFIG_THUNDERX_XCV) += thunder_xcv.o

ccflags-y += -Icsr/include
