#
# (C) Copyright 2014, Cavium Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-$(CONFIG_THUNDERX_BGX) += thunder_bgx.o
obj-$(CONFIG_THUNDERX_VNIC) += nic_main.o nicvf_queues.o nicvf_main.o
obj-$(CONFIG_THUNDERX_SMI) += thunderx_smi.o
obj-$(CONFIG_THUNDERX_XCV) += thunder_xcv.o

