# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2019
# Ramon Fried <ramon.fried@gmail.com>

obj-y += pci_ep-uclass.o
obj-$(CONFIG_PCIE_CADENCE_EP) += pcie-cadence-ep.o
obj-$(CONFIG_PCI_SANDBOX_EP) += sandbox-pci_ep.o
obj-$(CONFIG_PCIE_DW_MVEBU_EP) += pcie_dw_mvebu_ep.o pcie_mvebu_ep_uio.o
