#
# (C) Copyright 2018, Cavium Inc.
#
# SPDX-License-Identifier:	GPL-2.0+
#
obj-$(CONFIG_OCTEONTX2_CGX) += cgx_intf.o cgx.o nix_af.o nix.o
obj-$(CONFIG_OCTEONTX2_RVU) += rvu_pf.o rvu_af.o
#obj-y += cgx_intf.o cgx.o rvu_pf.o rvu_af.o
